// Curated list of supported currencies — types, codes, names, symbols, regions.
// Single source of truth: every other module references this list rather than
// re-declaring currency codes.
//
// Source: ISO 4217 active codes + a small whitelist of major cryptocurrencies.
// The fawazahmed0/exchange-api returns hundreds of obscure altcoin tokens
// (1inch, aave, akt, algo, amp, ape, …) which we deliberately do not surface.

export enum CurrencyCode {
  AED = "AED",
  AFN = "AFN",
  ALL = "ALL",
  AMD = "AMD",
  ANG = "ANG",
  AOA = "AOA",
  ARS = "ARS",
  AUD = "AUD",
  AWG = "AWG",
  AZN = "AZN",
  BAM = "BAM",
  BBD = "BBD",
  BDT = "BDT",
  BGN = "BGN",
  BHD = "BHD",
  BIF = "BIF",
  BMD = "BMD",
  BND = "BND",
  BOB = "BOB",
  BRL = "BRL",
  BSD = "BSD",
  BTN = "BTN",
  BWP = "BWP",
  BYN = "BYN",
  BZD = "BZD",
  CAD = "CAD",
  CDF = "CDF",
  CHF = "CHF",
  CLP = "CLP",
  CNY = "CNY",
  COP = "COP",
  CRC = "CRC",
  CUP = "CUP",
  CVE = "CVE",
  CZK = "CZK",
  DJF = "DJF",
  DKK = "DKK",
  DOP = "DOP",
  DZD = "DZD",
  EGP = "EGP",
  ERN = "ERN",
  ETB = "ETB",
  EUR = "EUR",
  FJD = "FJD",
  FKP = "FKP",
  GBP = "GBP",
  GEL = "GEL",
  GHS = "GHS",
  GIP = "GIP",
  GMD = "GMD",
  GNF = "GNF",
  GTQ = "GTQ",
  GYD = "GYD",
  HKD = "HKD",
  HNL = "HNL",
  HTG = "HTG",
  HUF = "HUF",
  IDR = "IDR",
  ILS = "ILS",
  INR = "INR",
  IQD = "IQD",
  IRR = "IRR",
  ISK = "ISK",
  JMD = "JMD",
  JOD = "JOD",
  JPY = "JPY",
  KES = "KES",
  KGS = "KGS",
  KHR = "KHR",
  KMF = "KMF",
  KPW = "KPW",
  KRW = "KRW",
  KWD = "KWD",
  KYD = "KYD",
  KZT = "KZT",
  LAK = "LAK",
  LBP = "LBP",
  LKR = "LKR",
  LRD = "LRD",
  LSL = "LSL",
  LYD = "LYD",
  MAD = "MAD",
  MDL = "MDL",
  MGA = "MGA",
  MKD = "MKD",
  MMK = "MMK",
  MNT = "MNT",
  MOP = "MOP",
  MRU = "MRU",
  MUR = "MUR",
  MVR = "MVR",
  MWK = "MWK",
  MXN = "MXN",
  MYR = "MYR",
  MZN = "MZN",
  NAD = "NAD",
  NGN = "NGN",
  NIO = "NIO",
  NOK = "NOK",
  NPR = "NPR",
  NZD = "NZD",
  OMR = "OMR",
  PAB = "PAB",
  PEN = "PEN",
  PGK = "PGK",
  PHP = "PHP",
  PKR = "PKR",
  PLN = "PLN",
  PYG = "PYG",
  QAR = "QAR",
  RON = "RON",
  RSD = "RSD",
  RUB = "RUB",
  RWF = "RWF",
  SAR = "SAR",
  SBD = "SBD",
  SCR = "SCR",
  SDG = "SDG",
  SEK = "SEK",
  SGD = "SGD",
  SHP = "SHP",
  SLE = "SLE",
  SOS = "SOS",
  SRD = "SRD",
  SSP = "SSP",
  STN = "STN",
  SVC = "SVC",
  SYP = "SYP",
  SZL = "SZL",
  THB = "THB",
  TJS = "TJS",
  TMT = "TMT",
  TND = "TND",
  TOP = "TOP",
  TRY = "TRY",
  TTD = "TTD",
  TWD = "TWD",
  TZS = "TZS",
  UAH = "UAH",
  UGX = "UGX",
  USD = "USD",
  UYU = "UYU",
  UZS = "UZS",
  VED = "VED",
  VND = "VND",
  VUV = "VUV",
  WST = "WST",
  XAF = "XAF",
  XCD = "XCD",
  XCG = "XCG",
  XOF = "XOF",
  XPF = "XPF",
  YER = "YER",
  ZAR = "ZAR",
  ZMW = "ZMW",
  ZWG = "ZWG",
  // Cryptocurrencies (whitelisted majors only)
  BTC = "BTC",
  ETH = "ETH",
  SOL = "SOL",
  USDC = "USDC",
  USDT = "USDT",
  XRP = "XRP",
  ADA = "ADA",
  DOGE = "DOGE",
}

export interface Currency {
  readonly code: CurrencyCode;
  readonly name: string;
  readonly symbol?: string;
  /** ISO 3166-1 alpha-2 region codes where this currency is the primary tender.
   *  Used to derive a default base from the user's locale. */
  readonly regions?: readonly string[];
}

export const CURRENCIES: readonly Currency[] = [
  { code: CurrencyCode.AED, name: "UAE Dirham", symbol: "د.إ", regions: ["AE"] },
  { code: CurrencyCode.AFN, name: "Afghan Afghani", symbol: "؋" },
  { code: CurrencyCode.ALL, name: "Albanian Lek" },
  { code: CurrencyCode.AMD, name: "Armenian Dram", symbol: "֏" },
  { code: CurrencyCode.ANG, name: "Netherlands Antillean Guilder" },
  { code: CurrencyCode.AOA, name: "Angolan Kwanza" },
  { code: CurrencyCode.ARS, name: "Argentine Peso", symbol: "AR$", regions: ["AR"] },
  { code: CurrencyCode.AUD, name: "Australian Dollar", symbol: "A$", regions: ["AU"] },
  { code: CurrencyCode.AWG, name: "Aruban Florin" },
  { code: CurrencyCode.AZN, name: "Azerbaijani Manat", symbol: "₼" },
  { code: CurrencyCode.BAM, name: "Bosnia-Herzegovina Convertible Mark" },
  { code: CurrencyCode.BBD, name: "Barbadian Dollar" },
  { code: CurrencyCode.BDT, name: "Bangladeshi Taka", symbol: "৳", regions: ["BD"] },
  { code: CurrencyCode.BGN, name: "Bulgarian Lev", regions: ["BG"] },
  { code: CurrencyCode.BHD, name: "Bahraini Dinar", symbol: "د.ب" },
  { code: CurrencyCode.BIF, name: "Burundian Franc" },
  { code: CurrencyCode.BMD, name: "Bermudan Dollar" },
  { code: CurrencyCode.BND, name: "Brunei Dollar" },
  { code: CurrencyCode.BOB, name: "Bolivian Boliviano" },
  { code: CurrencyCode.BRL, name: "Brazilian Real", symbol: "R$", regions: ["BR"] },
  { code: CurrencyCode.BSD, name: "Bahamian Dollar" },
  { code: CurrencyCode.BTN, name: "Bhutanese Ngultrum" },
  { code: CurrencyCode.BWP, name: "Botswanan Pula" },
  { code: CurrencyCode.BYN, name: "Belarusian Ruble" },
  { code: CurrencyCode.BZD, name: "Belize Dollar" },
  { code: CurrencyCode.CAD, name: "Canadian Dollar", symbol: "C$", regions: ["CA"] },
  { code: CurrencyCode.CDF, name: "Congolese Franc" },
  { code: CurrencyCode.CHF, name: "Swiss Franc", symbol: "Fr", regions: ["CH"] },
  { code: CurrencyCode.CLP, name: "Chilean Peso", symbol: "CL$", regions: ["CL"] },
  { code: CurrencyCode.CNY, name: "Chinese Yuan", symbol: "¥", regions: ["CN"] },
  { code: CurrencyCode.COP, name: "Colombian Peso", symbol: "Col$", regions: ["CO"] },
  { code: CurrencyCode.CRC, name: "Costa Rican Colón" },
  { code: CurrencyCode.CUP, name: "Cuban Peso" },
  { code: CurrencyCode.CVE, name: "Cape Verdean Escudo" },
  { code: CurrencyCode.CZK, name: "Czech Koruna", symbol: "Kč", regions: ["CZ"] },
  { code: CurrencyCode.DJF, name: "Djiboutian Franc" },
  { code: CurrencyCode.DKK, name: "Danish Krone", symbol: "kr", regions: ["DK"] },
  { code: CurrencyCode.DOP, name: "Dominican Peso" },
  { code: CurrencyCode.DZD, name: "Algerian Dinar", symbol: "د.ج" },
  { code: CurrencyCode.EGP, name: "Egyptian Pound", symbol: "E£", regions: ["EG"] },
  { code: CurrencyCode.ERN, name: "Eritrean Nakfa" },
  { code: CurrencyCode.ETB, name: "Ethiopian Birr" },
  {
    code: CurrencyCode.EUR,
    name: "Euro",
    symbol: "€",
    regions: [
      "IE",
      "DE",
      "FR",
      "ES",
      "IT",
      "NL",
      "BE",
      "AT",
      "PT",
      "FI",
      "GR",
      "LU",
      "SK",
      "SI",
      "LT",
      "LV",
      "EE",
      "MT",
      "CY",
      "HR",
    ],
  },
  { code: CurrencyCode.FJD, name: "Fijian Dollar" },
  { code: CurrencyCode.FKP, name: "Falkland Islands Pound" },
  { code: CurrencyCode.GBP, name: "British Pound", symbol: "£", regions: ["GB"] },
  { code: CurrencyCode.GEL, name: "Georgian Lari", symbol: "₾" },
  { code: CurrencyCode.GHS, name: "Ghanaian Cedi", symbol: "₵", regions: ["GH"] },
  { code: CurrencyCode.GIP, name: "Gibraltar Pound" },
  { code: CurrencyCode.GMD, name: "Gambian Dalasi" },
  { code: CurrencyCode.GNF, name: "Guinean Franc" },
  { code: CurrencyCode.GTQ, name: "Guatemalan Quetzal" },
  { code: CurrencyCode.GYD, name: "Guyanaese Dollar" },
  { code: CurrencyCode.HKD, name: "Hong Kong Dollar", symbol: "HK$", regions: ["HK"] },
  { code: CurrencyCode.HNL, name: "Honduran Lempira" },
  { code: CurrencyCode.HTG, name: "Haitian Gourde" },
  { code: CurrencyCode.HUF, name: "Hungarian Forint", symbol: "Ft", regions: ["HU"] },
  { code: CurrencyCode.IDR, name: "Indonesian Rupiah", symbol: "Rp", regions: ["ID"] },
  { code: CurrencyCode.ILS, name: "Israeli New Shekel", symbol: "₪", regions: ["IL"] },
  { code: CurrencyCode.INR, name: "Indian Rupee", symbol: "₹", regions: ["IN"] },
  { code: CurrencyCode.IQD, name: "Iraqi Dinar", symbol: "ع.د" },
  { code: CurrencyCode.IRR, name: "Iranian Rial", symbol: "﷼" },
  { code: CurrencyCode.ISK, name: "Icelandic Króna", symbol: "kr", regions: ["IS"] },
  { code: CurrencyCode.JMD, name: "Jamaican Dollar" },
  { code: CurrencyCode.JOD, name: "Jordanian Dinar" },
  { code: CurrencyCode.JPY, name: "Japanese Yen", symbol: "¥", regions: ["JP"] },
  { code: CurrencyCode.KES, name: "Kenyan Shilling", symbol: "KSh", regions: ["KE"] },
  { code: CurrencyCode.KGS, name: "Kyrgystani Som" },
  { code: CurrencyCode.KHR, name: "Cambodian Riel", symbol: "៛" },
  { code: CurrencyCode.KMF, name: "Comorian Franc" },
  { code: CurrencyCode.KPW, name: "North Korean Won" },
  { code: CurrencyCode.KRW, name: "South Korean Won", symbol: "₩", regions: ["KR"] },
  { code: CurrencyCode.KWD, name: "Kuwaiti Dinar", symbol: "د.ك" },
  { code: CurrencyCode.KYD, name: "Cayman Islands Dollar" },
  { code: CurrencyCode.KZT, name: "Kazakhstani Tenge", symbol: "₸" },
  { code: CurrencyCode.LAK, name: "Laotian Kip", symbol: "₭" },
  { code: CurrencyCode.LBP, name: "Lebanese Pound", symbol: "L£" },
  { code: CurrencyCode.LKR, name: "Sri Lankan Rupee", symbol: "Rs", regions: ["LK"] },
  { code: CurrencyCode.LRD, name: "Liberian Dollar" },
  { code: CurrencyCode.LSL, name: "Lesotho Loti" },
  { code: CurrencyCode.LYD, name: "Libyan Dinar" },
  { code: CurrencyCode.MAD, name: "Moroccan Dirham", symbol: "د.م.", regions: ["MA"] },
  { code: CurrencyCode.MDL, name: "Moldovan Leu" },
  { code: CurrencyCode.MGA, name: "Malagasy Ariary" },
  { code: CurrencyCode.MKD, name: "Macedonian Denar" },
  { code: CurrencyCode.MMK, name: "Myanma Kyat", symbol: "K" },
  { code: CurrencyCode.MNT, name: "Mongolian Tugrik", symbol: "₮" },
  { code: CurrencyCode.MOP, name: "Macanese Pataca" },
  { code: CurrencyCode.MRU, name: "Mauritanian Ouguiya" },
  { code: CurrencyCode.MUR, name: "Mauritian Rupee" },
  { code: CurrencyCode.MVR, name: "Maldivian Rufiyaa" },
  { code: CurrencyCode.MWK, name: "Malawian Kwacha" },
  { code: CurrencyCode.MXN, name: "Mexican Peso", symbol: "Mex$", regions: ["MX"] },
  { code: CurrencyCode.MYR, name: "Malaysian Ringgit", symbol: "RM", regions: ["MY"] },
  { code: CurrencyCode.MZN, name: "Mozambican Metical" },
  { code: CurrencyCode.NAD, name: "Namibian Dollar" },
  { code: CurrencyCode.NGN, name: "Nigerian Naira", symbol: "₦", regions: ["NG"] },
  { code: CurrencyCode.NIO, name: "Nicaraguan Córdoba" },
  { code: CurrencyCode.NOK, name: "Norwegian Krone", symbol: "kr", regions: ["NO"] },
  { code: CurrencyCode.NPR, name: "Nepalese Rupee", symbol: "Rs" },
  { code: CurrencyCode.NZD, name: "New Zealand Dollar", symbol: "NZ$", regions: ["NZ"] },
  { code: CurrencyCode.OMR, name: "Omani Rial" },
  { code: CurrencyCode.PAB, name: "Panamanian Balboa" },
  { code: CurrencyCode.PEN, name: "Peruvian Sol", regions: ["PE"] },
  { code: CurrencyCode.PGK, name: "Papua New Guinean Kina" },
  { code: CurrencyCode.PHP, name: "Philippine Peso", symbol: "₱", regions: ["PH"] },
  { code: CurrencyCode.PKR, name: "Pakistani Rupee", symbol: "₨", regions: ["PK"] },
  { code: CurrencyCode.PLN, name: "Polish Zloty", symbol: "zł", regions: ["PL"] },
  { code: CurrencyCode.PYG, name: "Paraguayan Guarani" },
  { code: CurrencyCode.QAR, name: "Qatari Rial", symbol: "﷼" },
  { code: CurrencyCode.RON, name: "Romanian Leu", regions: ["RO"] },
  { code: CurrencyCode.RSD, name: "Serbian Dinar" },
  { code: CurrencyCode.RUB, name: "Russian Ruble", symbol: "₽", regions: ["RU"] },
  { code: CurrencyCode.RWF, name: "Rwandan Franc" },
  { code: CurrencyCode.SAR, name: "Saudi Riyal", symbol: "﷼", regions: ["SA"] },
  { code: CurrencyCode.SBD, name: "Solomon Islands Dollar" },
  { code: CurrencyCode.SCR, name: "Seychellois Rupee" },
  { code: CurrencyCode.SDG, name: "Sudanese Pound" },
  { code: CurrencyCode.SEK, name: "Swedish Krona", symbol: "kr", regions: ["SE"] },
  { code: CurrencyCode.SGD, name: "Singapore Dollar", symbol: "S$", regions: ["SG"] },
  { code: CurrencyCode.SHP, name: "Saint Helena Pound" },
  { code: CurrencyCode.SLE, name: "Sierra Leonean Leone" },
  { code: CurrencyCode.SOS, name: "Somali Shilling" },
  { code: CurrencyCode.SRD, name: "Surinamese Dollar" },
  { code: CurrencyCode.SSP, name: "South Sudanese Pound" },
  { code: CurrencyCode.STN, name: "São Tomé & Príncipe Dobra" },
  { code: CurrencyCode.SVC, name: "Salvadoran Colón" },
  { code: CurrencyCode.SYP, name: "Syrian Pound" },
  { code: CurrencyCode.SZL, name: "Swazi Lilangeni" },
  { code: CurrencyCode.THB, name: "Thai Baht", symbol: "฿", regions: ["TH"] },
  { code: CurrencyCode.TJS, name: "Tajikistani Somoni" },
  { code: CurrencyCode.TMT, name: "Turkmenistani Manat" },
  { code: CurrencyCode.TND, name: "Tunisian Dinar", symbol: "د.ت" },
  { code: CurrencyCode.TOP, name: "Tongan Paʻanga" },
  { code: CurrencyCode.TRY, name: "Turkish Lira", symbol: "₺", regions: ["TR"] },
  { code: CurrencyCode.TTD, name: "Trinidad & Tobago Dollar" },
  { code: CurrencyCode.TWD, name: "New Taiwan Dollar", symbol: "NT$", regions: ["TW"] },
  { code: CurrencyCode.TZS, name: "Tanzanian Shilling", symbol: "TSh" },
  { code: CurrencyCode.UAH, name: "Ukrainian Hryvnia", symbol: "₴", regions: ["UA"] },
  { code: CurrencyCode.UGX, name: "Ugandan Shilling", symbol: "USh" },
  { code: CurrencyCode.USD, name: "US Dollar", symbol: "$", regions: ["US"] },
  { code: CurrencyCode.UYU, name: "Uruguayan Peso", symbol: "$U", regions: ["UY"] },
  { code: CurrencyCode.UZS, name: "Uzbekistani Som", symbol: "soʻm" },
  { code: CurrencyCode.VED, name: "Venezuelan Bolívar Soberano" },
  { code: CurrencyCode.VND, name: "Vietnamese Dong", symbol: "₫", regions: ["VN"] },
  { code: CurrencyCode.VUV, name: "Vanuatu Vatu" },
  { code: CurrencyCode.WST, name: "Samoan Tala" },
  { code: CurrencyCode.XAF, name: "Central African CFA Franc" },
  { code: CurrencyCode.XCD, name: "East Caribbean Dollar" },
  { code: CurrencyCode.XCG, name: "Caribbean Guilder" },
  { code: CurrencyCode.XOF, name: "West African CFA Franc" },
  { code: CurrencyCode.XPF, name: "CFP Franc" },
  { code: CurrencyCode.YER, name: "Yemeni Rial" },
  { code: CurrencyCode.ZAR, name: "South African Rand", symbol: "R", regions: ["ZA"] },
  { code: CurrencyCode.ZMW, name: "Zambian Kwacha" },
  { code: CurrencyCode.ZWG, name: "Zimbabwean Gold" },
  // Cryptocurrencies (whitelisted majors only)
  { code: CurrencyCode.BTC, name: "Bitcoin", symbol: "₿" },
  { code: CurrencyCode.ETH, name: "Ethereum", symbol: "Ξ" },
  { code: CurrencyCode.SOL, name: "Solana", symbol: "◎" },
  { code: CurrencyCode.USDC, name: "USD Coin", symbol: "$" },
  { code: CurrencyCode.USDT, name: "Tether", symbol: "₮" },
  { code: CurrencyCode.XRP, name: "XRP", symbol: "✕" },
  { code: CurrencyCode.ADA, name: "Cardano", symbol: "₳" },
  { code: CurrencyCode.DOGE, name: "Dogecoin", symbol: "Ð" },
];

export const SUPPORTED_CODES: ReadonlySet<string> = new Set(
  CURRENCIES.map((currency) => currency.code),
);

export const CURRENCY_NAMES: Readonly<Record<string, string>> = Object.fromEntries(
  CURRENCIES.map((currency) => [currency.code, currency.name]),
);

export const CURRENCY_SYMBOLS: Readonly<Record<string, string>> = Object.fromEntries(
  CURRENCIES.filter(
    (currency): currency is Currency & { symbol: string } => currency.symbol !== undefined,
  ).map((currency) => [currency.code, currency.symbol]),
);
