/**
 * Number format catalog.
 *
 * Generated by formatting `1234567.89` and `-1234567.89` with every BCP-47
 * tag that the runtime `Intl` engine supports, sanitising the output, and
 * deduplicating by the (positive, negative) example pair. Each unique pair
 * becomes a selectable "number format" in settings; locales whose output
 * collapses into the same pair are grouped under `matchingLocales`.
 *
 * The user picks a format (not a locale) in settings. We use the format's
 * representative `locale` to render plain numbers, and we override the
 * decimal/group separators of currency output (which keeps the currency's
 * home-locale symbol position) with the format's separators.
 */

import { getBrowserLanguages } from "./locale";
import { sanitize } from "./utils/sanitizeString";

export interface NumberFormat {
  /** All BCP-47 tags whose `Intl.NumberFormat` output sanitises to the same
   *  example pair. Used when matching `navigator.languages` to a default. */
  matchingLocales: readonly string[];
  /** Sanitised `1234567.89` rendered in this format. Doubles as the UI
   *  label in the format dropdown. */
  positiveExample: string;
  /** Sanitised `-1234567.89` rendered in this format. */
  negativeExample: string;
  /** Decimal separator character (`.` or `,`). */
  decimal: string;
  /** Group separator character (`.`, `,`, ` `, `'`) or `""` when the
   *  locale doesn't group. */
  group: string;
}

/** Recover the decimal and group separator characters from a sanitised
 *  formatted number. The rightmost gap between digit runs is the decimal
 *  (the probe value `1234567.89` always ends with a fractional part);
 *  earlier gaps are the group separator. */
export function inferSeparators(sample: string): { decimal: string; group: string } {
  const digitRuns = [...sample.matchAll(/\d+/g)];
  if (digitRuns.length < 2) {
    return { decimal: ".", group: "" };
  }
  const gaps: string[] = [];
  for (let i = 1; i < digitRuns.length; i++) {
    const prev = digitRuns[i - 1];
    const curr = digitRuns[i];
    gaps.push(sample.slice(prev.index! + prev[0].length, curr.index!));
  }
  return {
    decimal: gaps[gaps.length - 1],
    group: gaps.length > 1 ? gaps[0] : "",
  };
}

const POSITIVE_PROBE = 1234567.89;
const NEGATIVE_PROBE = -1234567.89;

/** Two-letter ISO 639-1 codes with significant CLDR coverage. Crossed with
 *  every region supported by the runtime, plus the language-only forms,
 *  this generates roughly 15–20k candidate BCP-47 tags. The filter step
 *  (`Intl.NumberFormat.supportedLocalesOf`) keeps only those the runtime
 *  actually knows about, which is typically ~5k. */
const CANDIDATE_LANGUAGES = [
  "en",
  "de",
  "fr",
  "es",
  "pt",
  "it",
  "nl",
  "sv",
  "no",
  "nb",
  "da",
  "fi",
  "is",
  "pl",
  "cs",
  "sk",
  "sl",
  "hr",
  "sr",
  "bg",
  "ro",
  "hu",
  "et",
  "lv",
  "lt",
  "mt",
  "ga",
  "el",
  "ru",
  "uk",
  "be",
  "kk",
  "uz",
  "tr",
  "az",
  "ka",
  "hy",
  "ar",
  "fa",
  "ur",
  "he",
  "hi",
  "bn",
  "ta",
  "te",
  "ml",
  "kn",
  "gu",
  "mr",
  "pa",
  "si",
  "ne",
  "as",
  "or",
  "th",
  "vi",
  "km",
  "lo",
  "my",
  "id",
  "ms",
  "tl",
  "jv",
  "ja",
  "ko",
  "zh",
  "yue",
  "am",
  "sw",
  "zu",
  "af",
  "yo",
  "ig",
  "ha",
  "so",
  "eu",
  "ca",
  "gl",
];

/** Fallback ISO 3166-1 alpha-2 region list, used when
 *  `Intl.supportedValuesOf("region")` is unavailable. */
const FALLBACK_REGIONS = [
  "US",
  "GB",
  "AU",
  "CA",
  "NZ",
  "IE",
  "ZA",
  "IN",
  "SG",
  "HK",
  "DE",
  "AT",
  "CH",
  "LI",
  "BE",
  "NL",
  "LU",
  "FR",
  "MC",
  "ES",
  "MX",
  "AR",
  "CO",
  "CL",
  "PE",
  "VE",
  "UY",
  "PY",
  "BO",
  "EC",
  "DO",
  "GT",
  "IT",
  "SM",
  "VA",
  "PT",
  "BR",
  "SE",
  "NO",
  "DK",
  "FI",
  "IS",
  "PL",
  "CZ",
  "SK",
  "SI",
  "HR",
  "RS",
  "BG",
  "RO",
  "HU",
  "EE",
  "LV",
  "LT",
  "MT",
  "GR",
  "RU",
  "UA",
  "BY",
  "KZ",
  "UZ",
  "TR",
  "AZ",
  "GE",
  "AM",
  "SA",
  "AE",
  "EG",
  "IR",
  "PK",
  "IQ",
  "JO",
  "LB",
  "SY",
  "MA",
  "TN",
  "DZ",
  "IL",
  "BD",
  "LK",
  "NP",
  "TH",
  "VN",
  "KH",
  "LA",
  "MM",
  "ID",
  "MY",
  "PH",
  "JP",
  "KR",
  "CN",
  "TW",
  "ET",
  "KE",
  "TZ",
  "UG",
  "ZA",
  "NG",
  "GH",
];

function getRegions(): readonly string[] {
  try {
    const fn = (Intl as { supportedValuesOf?: (key: string) => string[] }).supportedValuesOf;
    if (typeof fn === "function") {
      return fn("region");
    }
  } catch {
    // fall through
  }
  return FALLBACK_REGIONS;
}

function generateCandidateLocales(): string[] {
  const out: string[] = [...CANDIDATE_LANGUAGES];
  const regions = getRegions();
  for (const lang of CANDIDATE_LANGUAGES) {
    for (const region of regions) {
      out.push(`${lang}-${region}`);
    }
  }
  return out;
}

function formatProbe(locale: string, value: number): string | null {
  try {
    const raw = new Intl.NumberFormat(locale).format(value);
    return sanitize(raw) ?? null;
  } catch {
    return null;
  }
}

let cached: readonly NumberFormat[] | null = null;

/** Build (and cache) the deduplicated list of number formats. Sorted by
 *  positive example for stable UI ordering. */
export function getNumberFormats(): readonly NumberFormat[] {
  if (cached) {
    return cached;
  }

  const candidates = generateCandidateLocales();
  let supported: readonly string[];
  try {
    supported = Intl.NumberFormat.supportedLocalesOf(candidates);
  } catch {
    supported = ["en-US"];
  }

  interface Bucket {
    positive: string;
    negative: string;
    locales: string[];
  }
  const byKey = new Map<string, Bucket>();

  for (const locale of supported) {
    const positive = formatProbe(locale, POSITIVE_PROBE);
    const negative = formatProbe(locale, NEGATIVE_PROBE);
    if (positive === null || negative === null) {
      continue;
    }
    const key = `${positive}|${negative}`;
    const existing = byKey.get(key);
    if (existing) {
      existing.locales.push(locale);
    } else {
      byKey.set(key, { positive, negative, locales: [locale] });
    }
  }

  const formats: NumberFormat[] = [];
  for (const { positive, negative, locales } of byKey.values()) {
    const { decimal, group } = inferSeparators(positive);
    formats.push({
      positiveExample: positive,
      negativeExample: negative,
      decimal,
      group,
      matchingLocales: locales,
    });
  }
  formats.sort((a, b) => a.positiveExample.localeCompare(b.positiveExample));
  cached = formats;
  return cached;
}

/** Look up a format by its representative locale. Returns `null` for
 *  unknown ids (e.g. a persisted id from a removed locale). */
export function getNumberFormatByLocale(locale: string): NumberFormat | null {
  return getNumberFormats().find((f) => f.matchingLocales.some((l) => l === locale)) ?? null;
}

/** Pick a default format for the current browser. Walks
 *  `navigator.languages` in order, returning the first format whose
 *  `matchingLocales` contains the language tag, or any locale starting
 *  with the language part. Falls back to the en-US format. */
export function detectDefaultFormat(): NumberFormat {
  const formats = getNumberFormats();
  const langs = getBrowserLanguages();

  for (const lang of langs) {
    const direct = formats.find((f) => f.matchingLocales.includes(lang));
    if (direct) {
      return direct;
    }
    const langPart = lang.split("-")[0];
    const prefix = formats.find(
      (f) =>
        f.matchingLocales.includes(langPart) ||
        f.matchingLocales.some((l) => l.startsWith(`${langPart}-`)),
    );
    if (prefix) {
      return prefix;
    }
  }

  return (
    formats.find((f) => f.matchingLocales.some((l) => l === "en-US" || l === "en")) ?? formats[0]
  );
}
